### ISSUE TITLE
Server TPS drops significantly after installing the plugin

### ISSUE THREAD

**Issue by CosmicDreamsOfCode** [SeanOMik/TamableFoxes#10]
Not sure what else to say.
Running 1.15.2 with Spigot on an Aternos server but not long after installing the plugin the server ended up running 1500+ ticks behind.

**Comment by SeanOMik** [comment]
Not sure what could've caused this. When you say "not long after" do you mean without any changes to other plugins or their configuration?

Did you try to remove the plugin to see if that would resolve your TPS issues?

**Comment by CosmicDreamsOfCode** [comment]
Basically a few minutes after starting up the server the TPS starts tanking as long as the plugin is enabled. 
It's the only plugin on the server and no changes have been made to the config.
I do have 3 foxes tamed in my house if that makes any difference.

**Comment by Foxersthe** [comment]
I'm having the same exact issue. I can't really use the plugin because of such slowdown.

**Comment by SeanOMik** [comment]
I honestly have zero idea what would cause the low TPS since nothing is running all the time like other servers.

**Comment by SeanOMik** [comment]
I've never encountered this issue also. I would leave my test server open for 30 minutes at a time before I would have to reboot it and there were never any TPS drops.

**Comment by itsfolf** [comment]
@SeanOMik Have a look on my new implementation of the plugin, it uses completely vanilla methods so it needs no custom loading or saving making performance much better, I've changed a few things tho so I can't PR
https://github.com/fuwwy/TamableFoxes

**Comment by SeanOMik** [comment]
Looks great, I'll pull it and take a deeper look at it. Is there a way you could make a change log for the things you changed? The change log doesn't need to be very detailed, it will just be used in the spigot update text.

**Comment by SeanOMik** [comment]
A few days ago I released a new version1.6.0-SNAPSHOT. It would be great if you could test it @CosmicDreamsOfCode and @Foxersthe.

**Comment by SeanOMik** [comment]
I don't think this is an issue anymore. If it is, create a new issue.
