### ISSUE TITLE
it can not run on the latest paper server under Ubuntu18 java14

### ISSUE THREAD

**Issue by chen-Futuro** [SeanOMik/TamableFoxes#12]
I found that it can not run on the latest paper server under Ubuntu18 java14 environment, but it can be done under java1.8 environment, the error message that the server appears is Failed to replace tamable fox entity!

**Comment by SeanOMik** [comment]
Please read the warning on the spigot page: ```WARNING: Look at the below table to see what version you can download. PaperMC is not guaranteed to work! If your MC version is not specified, its not supported! Don't use a java version newer than Java 11! Do not reload the plugin! Please don't review one star because you don't follow this advice!```

I mean its the first line in the [resource](https://www.spigotmc.org/resources/tamable-foxes-1-14-2-1-15-x.69537/).
