### ISSUE TITLE
Duplicatable Buckets

### ISSUE THREAD

**Issue by ghost** [SeanOMik/TamableFoxes#13]
If you shift right click a fox with a bucket; the bucket becomes empty but the fox is holding a filled one.
You can pick it back up afterward and have one extra bucket.

Maybe add a blacklist for the items foxes can pick up?

Video showcasing bug [here](https://streamable.com/bf55qh).

**Comment by SeanOMik** [comment]
Oops, this issue is old. I'll take a look at it. Thanks for submitting an issue!

**Comment by SeanOMik** [comment]
The new release fixed it: https://github.com/SeanOMik/TamableFoxes/releases/tag/1.6.1-SNAPSHOT
