### ISSUE TITLE
[ISSUE] Ticking entity & Server Crash

### ISSUE THREAD

**Issue by GamingWubba93** [SeanOMik/TamableFoxes#15]
**Describe the bug**
Was running around a village and heading back to my Nether Portal when all of a sudden I was kicked from my server with a "forcibly closed server issue" 

**To Reproduce**
It appears that this issue happened when I was around wolves/foxes?  

**Console Log**
[2020-07-17-3.log.gz](https://github.com/SeanOMik/TamableFoxes/files/4935237/2020-07-17-3.log.gz)

**Crash Log**
[crash-2020-07-17_01.20.22-server.txt](https://github.com/SeanOMik/TamableFoxes/files/4935236/crash-2020-07-17_01.20.22-server.txt)

**Server Information (please complete the following information):**
 - Minecraft Version Spigot 1.15.2
- Plugin Version v1.7-SNAPSHOT

**Comment by SeanOMik** [comment]
I'll take a look at it later tonight

**Comment by SeanOMik** [comment]
I just fixed it. I made a typo and it made the 1.15 plugin version check for some 1.16 entities. I'll be making a release soon.

**Comment by SeanOMik** [comment]
Here's the release: https://github.com/SeanOMik/TamableFoxes/releases/tag/1.7.1-SNAPSHOT
