### ISSUE TITLE
Multiplayer Server Issue

### ISSUE THREAD

**Issue by OhJeepers** [SeanOMik/TamableFoxes#17]
Hi, I'm having an issue with the tamable foxes plugin on my server that I run with my friends. I'm the only one able to tame foxes, I'm also the only one with op. Any help would be greatly appreciated

**Comment by SeanOMik** [comment]
You need to give the players the permission `tamablefoxes.tame`. I recommend using LuckPerms as a permission manager, but use which ever one you prefer.
