### ISSUE TITLE
Server Errors

### ISSUE THREAD

**Issue by SavagePanda116** [SeanOMik/TamableFoxes#20]
Hi! I love this plugin and it works well. But we've had the server crash a few times since installing it. I'm not 100% sure that is it from this plugin, but this was one of the last errors received from the console before the crash each time:

Caused by: java.lang.NullPointerException
	at net.seanomik.tamablefoxes.versions.version_1_16_R2.EntityTamableFox.loadData(EntityTamableFox.java:191) ~[?:?]
	at net.minecraft.server.v1_16_R2.Entity.load(Entity.java:1696) ~[patched_1.16.2.jar:git-Paper-161]

Nobody had been using the plugin specifically when each crashed happened, as far as I know. It's not an urgent issue, it has only happened a few times and my community is very understanding :) I'll attach our log if it'll help fix the issue in the future.
[2020-09-03-3.log](https://github.com/SeanOMik/TamableFoxes/files/5171015/2020-09-03-3.log)

**Comment by SeanOMik** [comment]
I think I fixed the error just by looking at the code. I compiled it and was wondering if you could test it?

Just leave the server running with the new version for however long it would usually take for the server to crash, and tell me if you guys experience any crashes or not after that time period.

[Here's the download!](https://drive.google.com/file/d/1EbYE7pYlqSTEQFLUA4Yl5zrK5qimPtB2/view?usp=sharing)

**Comment by SavagePanda116** [comment]
For some reason I didn't get an email update when you posted, sorry! Thanks again for fixing so quickly. We just realized that Fox Spawners weren't working and were creating errors in the console, so I checked back and applied this update, which fixed that :)

**Comment by SeanOMik** [comment]
Ah, so the issue happened when it would try to spawn foxes in the world?

**Comment by SavagePanda116** [comment]
That's what it seemed like, but it seems to be completely fixed now :D.

We have been having issues with Name Tags not working though, on any other tamed animal besides foxes. It started when we uploaded this plugin and I was reading the reviews and someone said that they were having this issue as well and that they thought it could be this plugin. 

It's actually really weird. If I don't add a name to my fox when I tame it, then I can use a name tag on it and it works. Name tags work on untamed animals, like sheep and turtles. But if I tame a cat or dog and try to put a name tag on it, it doesn't work. BUT if I put a name tag on someone else's tamed pet, it'll show up for me as long as they aren't in the area. If they aren't around, then I can see the name tags that I put on their pets. And it's the same if I name my pets, other players can see the names, but only if I'm not around, and I can't see my own pets names.

No errors are appearing in console.
I'm sorry for reporting so many errors, we really do love your plugins :D

**Comment by SeanOMik** [comment]
That is a super weird bug, I'll close this issue and make a new issue talking about the name tag stuff. You can just copy and paste what you said here.

Happy that you love my plugins, and thanks for reporting bugs!
