### ISSUE TITLE
Name Tag Bug

### ISSUE THREAD

**Issue by SavagePanda116** [SeanOMik/TamableFoxes#21]
We have been having issues with Name Tags not working on any other tamed animal besides foxes. It started when we uploaded this plugin, I was also reading the reviews and someone said that they were having this issue as well and that they thought it could be this plugin.

It's actually really weird. If I don't add a name to my fox when I tame it, then I can use a name tag on it and it works. Name tags work on untamed animals, like sheep and turtles. But if I tame a cat or dog and try to put a name tag on it, it doesn't work. BUT if I put a name tag on someone else's tamed pet, it'll show up for me as long as they aren't in the area. If they aren't around, then I can see the name tags that I put on their pets. And it's the same if I name my pets, other players can see the names, but only if I'm not around, and I can't see my own pets names.

No errors are appearing in console.
I'm sorry for reporting so many errors, we really do love your plugins :D

**Comment by SeanOMik** [comment]
Thanks for creating a separate issue for this, I'll take a look at it soon.

**Comment by SeanOMik** [comment]
Got some free time to try to find reproduce the bug, but I cant. Is there any other plugin that may interfere with name tags? If you don't think so, just send a list, or a zip file, of plugins and I'll test my plugin with them.

**Comment by SavagePanda116** [comment]
I'm so sorry, I took some time off from server stuff! I don't think any of our plugins have anything to do with name tags.

I tried to create a zip for you, but it's telling me that the file is too large! Is there another way that I can send it to make it easier for you? We have a lot of plugins!! Here is a screenshot when I use /plugins. Advanced Portals, Alt Detector, and Amazing Fishing are cut off at the top. 
![image](https://user-images.githubusercontent.com/65567411/92828403-fe995500-f3a0-11ea-81aa-1fca96d11c77.png)

**Comment by SeanOMik** [comment]
Is GitHub saying the file is too large? If it is, you could just upload the files on a service like Dropbox, Google Drive, etc.

**Comment by SavagePanda116** [comment]
I tried Google Drive, hopefully this works: https://drive.google.com/drive/folders/1VtDk8-8bSqiO0GZvcqSROC65i5yA5HCb?usp=sharing

**Comment by SeanOMik** [comment]
I'm still not encountering the issue. Maybe you are inputting some special characters or something in the nametag name?

**Comment by SavagePanda116** [comment]
I've tried it without any characters, just normally renaming a name tag. It looks like it's mostly interacting with Grief Prevention because if I put a name tag on a tamed wolf, it doesn't appear for me or anyone near me, but if I leave my claim then everyone else can see the name. It only happens with tamed animals when the owner of the animal and claim is within the claim.

**Comment by SeanOMik** [comment]
That sounds like its something to do with Grief prevention. What if you try to name an animal outside of a claim?

**Comment by SavagePanda116** [comment]
Name tags still don't show up on tamed pets while owner is around outside of their claim :(

**Comment by SavagePanda116** [comment]
It looks like the latest update fixed this!!

**Comment by SeanOMik** [comment]
Version [1.7.6-Snapshot](https://github.com/SeanOMik/TamableFoxes/releases/tag/1.7.6-SNAPSHOT)? It must have been some weird thing with Java. Well, It's good that it's working, I'll close this issue now.
