### ISSUE TITLE
Errors on Tuinity

### ISSUE THREAD

**Issue by MastoryMd5** [SeanOMik/TamableFoxes#22]
In my server using Tuinity 1.16.2 i get this error https://hastebin.com/hajibihomu.bash

**Comment by SeanOMik** [comment]
I don't know what Tuinity is, but these errors look similar to what someone else was getting in #20 which was fixed in the [latest release.](https://github.com/SeanOMik/TamableFoxes/releases/tag/1.7.4-SNAPSHOT) Try that and tell me if the errors are gone.
