### ISSUE TITLE
[BUG] Broken with paperspigot

### ISSUE THREAD

**Issue by melody-rs** [SeanOMik/TamableFoxes#23]
I need to use paper spigot on my server as it's the only 1.16.2 server that supports bukkit and spigot plugins, but also fixes portal interrupts. 
All of my plugins work just fine, well, except for tamable foxes. I'm not exactly too sure why, but the plugin is just broken. Commands don't work, (no detailed error posted to log or console), foxes aren't tamable, and previously tamed foxes are untamed.
I know I'm a fairly niche use case, but I'd like to get this resolved.

**Comment by SeanOMik** [comment]
Post your entire server log. I've tested the plugin on paper and it's worked fine before

**Comment by melody-rs** [comment]
[latest.log](https://github.com/SeanOMik/TamableFoxes/files/5186316/latest.log)

**Comment by fionera** [comment]
Can confirm the issue, since I have the same error. I think its this line
```
[22:44:45] [Server thread/INFO]: [Tamable Foxes] Registering entity for MC Version v1_16_R2...
[22:44:45] [Server thread/INFO]: [Tamable Foxes] Failed to replace tamable fox entity!
```

**Comment by SeanOMik** [comment]
What Java version are you guys running? You need to make sure it's not newer than Java 11

**Comment by melody-rs** [comment]
Tried on Java 8 and Java 14. I need to run the server on Java 14 because one of the plugins was complied with it, but the issue still persists when using Java 8.

**Comment by fionera** [comment]
I feel stupid now. Currently running Java 14. With 11 it works

**Comment by SeanOMik** [comment]
@fionera Np, I forgot to add the warning on the github, but it was on the spigot. Glad its working now

**Comment by SeanOMik** [comment]
@Speak2Erase I'll try 1.16.2 with Java 8 and see if I run into any issues

**Comment by melody-rs** [comment]
Even still, I can't use Java 8 to run my server because one of my plugins (SimpleFormatting), was compiled in a more recent java version.
So it's either downgrading my java to get this plugin working, or stay on Java 14 to keep simple formatting working. Plus, I've noticed my server runs a bit better with java 14 than java 8 does.

**Comment by fionera** [comment]
@SeanOMik I just saw why it doesnt work with Java 14 and will try to fix that :)

**Comment by SeanOMik** [comment]
@Speak2Erase Maybe you could try to use Java 11?

**Comment by melody-rs** [comment]
I guess.

**Comment by SeanOMik** [comment]
@fionera I don't think there is a way to do it on Java 14. irrc its because I'm using reflection to change a field to not be final when registering the entity. But if you find a way to fix it that would be awesome!

**Comment by SeanOMik** [comment]
@fionera You wanna compile that pull request and give the .jar to Speak2Erase so we can see if it will work for him?

**Comment by melody-rs** [comment]
I can go ahead and try to compile it myself if need be

**Comment by fionera** [comment]
Sure :) https://trash.ctdo.de/file/a6771d73

**Comment by melody-rs** [comment]
wait nvm

**Comment by melody-rs** [comment]
it worked
[crash-2020-09-08_12.23.25-server.txt](https://github.com/SeanOMik/TamableFoxes/files/5190588/crash-2020-09-08_12.23.25-server.txt)
 the server crashed when i tried to tame a fox
When I restart, it works just fine, so my guess is it's an issue with the naming?

**Comment by fionera** [comment]
You are probably missing AnvilGUI

**Comment by SeanOMik** [comment]
AnvilGUI should be shaded into the jar. That's how I had it setup before

**Comment by fionera** [comment]
Yeah I uploaded the unshaded file :D This is the correct one https://trash.ctdo.de/file/5181d21b

**Comment by melody-rs** [comment]
Thx

**Comment by SeanOMik** [comment]
Okay, seems like that works, so I'm gonna close the issue, later tonight I'll merge the code and create a release with the update.
