### ISSUE TITLE
I can't work with JER. Is the JDK required?

### ISSUE THREAD

**Issue by SnowBees** [SeanOMik/TamableFoxes#25]
Can you manage this error?
https://pastebin.com/n2VPjcei

I happened to see this plug-in and was fascinated by it.
However, I get an error when starting the server.
I got an error only with jre-8u261-windows-x64, so I put in jdk-14.0.2_windows-x64_bin, but the error continued as well.

So I deleted the JRE and unified the version, and it started, but it seems that another plugin does not support it, so I would like to know the solution.

The plugin seems to cause a Core error in Bank.
https://pastebin.com/YycE4Cw2

https://www.spigotmc.org/resources/bank-1-16-sale-30-off.3556/
https://www.spigotmc.org/resources/core.56780/

Is it possible to make it work only with JRE?

**Comment by SeanOMik** [comment]
I think its because I compiled with a too new version of JDK let me try to fix it

**Comment by SeanOMik** [comment]
Okay, pretty sure I fixed it, [download the new release](https://github.com/SeanOMik/TamableFoxes/releases/tag/1.7.6-SNAPSHOT)!
