### ISSUE TITLE
Fox limits

### ISSUE THREAD

**Issue by Verdux** [SeanOMik/TamableFoxes#26]
Can we implement a limit on the amount of Fox's a player can tame or additionally how many can follow the player at once? I currently have a limit on Wolfs but players have started to bypass this by using Fox's instead.

**Comment by SeanOMik** [comment]
Hm. I'm not sure how I could limit the number of foxes following the player, but it should be pretty easy to add a limit to the number of foxes a player can tame. I'll work on that when I get some free time. Thanks!

**Comment by odiffey** [comment]
Thank you for adding this feature, could we also have a permission to bypass the set limit please? e.g. tamablefoxes.unlimited

**Comment by SeanOMik** [comment]
I didn't think about that. I'll work on that right now since I have some free time

**Comment by SeanOMik** [comment]
Done, download the new release [here](https://github.com/SeanOMik/TamableFoxes/releases/tag/1.7.8-SNAPSHOT).
