### ISSUE TITLE
PETM (Pet manager) and other pet manager plugins don't work with tamable foxes

### ISSUE THREAD

**Issue by melody-rs** [SeanOMik/TamableFoxes#27]
Simply put the plugin refuses to recognize tamable foxes as pets. Not sure if this counts as a bug or enhancement.

**Comment by SeanOMik** [comment]
This is an issue with the pet manager plugins themselves. Their plugins don't detect the custom entity. I will, however, try to contact a developer of PETM to see if we could work together to add support for this plugin.
