### ISSUE TITLE
Suggestion: Foxes sleep on player beds when their owners are in them

### ISSUE THREAD

**Issue by melody-rs** [SeanOMik/TamableFoxes#28]
A player on my server suggested this, and I think it'd be a pretty neat/cute thing to have. foxes already have a sleeping pose so I wouldn't see it being that hard to implement.

**Comment by SeanOMik** [comment]
I think currently, that they sleep on the ground when the player sleeps. But it would be cool to have them sleep on the bed as cats do.

**Comment by SeanOMik** [comment]
This has been implemented in the latest [release](https://github.com/SeanOMik/TamableFoxes/releases)!
