### ISSUE TITLE
1.16.4

### ISSUE THREAD

**Issue by Castiella** [SeanOMik/TamableFoxes#29]
[Tamable Foxes] This plugin version only supports Spigot 1.14-1.16.2! Disabling plugin! Make sure your Java version is no newer than Java 11!

Will you be updating to 1.16.4?

**Comment by SeanOMik** [comment]
Yes, I will be updating it to 1.16.4 soon

**Comment by SeanOMik** [comment]
Updated for 1.16.4, [download here](https://github.com/SeanOMik/TamableFoxes/releases/tag/1.8-SNAPSHOT).
