### ISSUE TITLE
Debugging Statement left in release

### ISSUE THREAD

**Issue by nugycal** [SeanOMik/TamableFoxes#3]
Line 154 of src/main/java/net/seanomik/tamablefoxes/TamableFoxes.java:
 `player.sendMessage(entity.getUniqueId().toString());`

Could this line please be removed from the release jar?

**Comment by SeanOMik** [comment]
Newest release just fixed that, sorry!

**Comment by SeanOMik** [comment]
Newest release just fixed that, sorry!
