### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Castiella** [SeanOMik/TamableFoxes#30]
Cant tell if this is a crash caused by TF or quests, could you please tell me? 

[eefwefwefwe.txt](https://github.com/SeanOMik/TamableFoxes/files/5562605/eefwefwefwe.txt)

**Comment by SeanOMik** [comment]
It looks like its due to QuestsGUI since my plugin loads AnvilGUI from QuestsGUI which uses an older version of AnvilGUI. Hopefully that makes sense. Contact the dev of QuestsGUI and tell me if they don't think its their plugin's fault.

**Comment by SeanOMik** [comment]
Dead issue
