### ISSUE TITLE
Does not enable on 1.16.4

### ISSUE THREAD

**Issue by SavagePanda116** [SeanOMik/TamableFoxes#31]
The Tamable Foxes plugin does not enable on 1.16.4, everyone has lost all of their tamed foxes, it is a sad day :(

**Comment by SeanOMik** [comment]
I'll take a look, in the mean time, maybe you could revert back to an older backup

**Comment by SeanOMik** [comment]
It works fine for me. Could you send a console log?

**Comment by SavagePanda116** [comment]
Here is a log from today, it still is not enabling. 
[latest.log](https://github.com/SeanOMik/TamableFoxes/files/5575385/latest.log)

**Comment by SeanOMik** [comment]
Looks like you're using 1.7.8-SNAPSHOT which doesn't support 1.16.4, you need to use [1.8-SNAPSHOT](https://github.com/SeanOMik/TamableFoxes/releases/tag/1.8-SNAPSHOT).

**Comment by SavagePanda116** [comment]
OH! That would explain it! I'm so sorry, I swore I was using the latest version. Thank you!

**Comment by SeanOMik** [comment]
No problem, enjoy!
