### ISSUE TITLE
Foxes slide after making them sit

### ISSUE THREAD

**Issue by energy-sync** [SeanOMik/TamableFoxes#32]
If the fox is walking when I click on it to sit down, it slides until it hits something or I make it stand up again.

https://user-images.githubusercontent.com/42476104/102928989-be4d7680-4467-11eb-8d67-3c2d8b11fdf2.mp4

**Comment by SeanOMik** [comment]
I'm aware of this, I've spent hours trying to figure it out and I've never been able to find out what causes it. It's been a while since I've taken a look at it so I'll look again soon.

**Comment by SeanOMik** [comment]
Fixed on [latest release](https://github.com/SeanOMik/TamableFoxes/releases/tag/1.8.1-SNAPSHOT).
