### ISSUE TITLE
Unknown issue

### ISSUE THREAD

**Issue by Natarager** [SeanOMik/TamableFoxes#33]
Hello! Unfortunately I got this message, in game it says Failed to spawn fox. Server is running on Mohist 1.16.4 modded server. By the way are you going to release mod for PC version of minecraft, is that even possible? 
Natarager issued server command: /spawntamablefox red
> [K[[36;1m04:07:17 [33;1mWARN]: [33;1mjava.lang.ClassCastException: class net.minecraft.entity.passive.FoxEntity cannot be cast to class net.seanomik.tamablefoxes.versions.version_1_16_R3.EntityTamableFox (net.minecraft.entity.passive.FoxEntity is in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @5c448433; net.seanomik.tamablefoxes.versions.version_1_16_R3.EntityTamableFox is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @4b854ba0)
> [K[[36;1m04:07:17 [33;1mWARN]: [33;1m at net.seanomik.tamablefoxes.versions.version_1_16_R3.NMSInterface_1_16_R3.spawnTamableFox(NMSInterface_1_16_R3.java:33)
> [K[[36;1m04:07:17 [33;1mWARN]: [33;1m at net.seanomik.tamablefoxes.CommandSpawnTamableFox.onCommand(CommandSpawnTamableFox.java:40)
> [K[[36;1m04:07:17 [33;1mWARN]: [33;1m at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
> [K[[36;1m04:07:17 [33;1mWARN]: [33;1m at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:160)
> [K[[36;1m04:07:17 [33;1mWARN]: [33;1m at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:669)
> [K[[36;1m04:07:17 [33;1mWARN]: [33;1m at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandler.java:1799)
> [K[[36;1m04:07:17 [33;1mWARN]: [33;1m at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:1646)
> [K[[36;1m04:07:17 [33;1mWARN]: [33;1m at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:38)
> [K[[36;1m04:07:17 [33;1mWARN]: [33;1m at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:8)
> [K[[36;1m04:07:17 [33;1mWARN]: [33;1m at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:22)
> [K[[36;1m04:07:17 [33;1mWARN]: [33;1m at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
> [K[[36;1m04:07:17 [33;1mWARN]: [33;1m at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:136)
> [K[[36;1m04:07:17 [33;1mWARN]: [33;1m at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
> [K[[36;1m04:07:17 [33;1mWARN]: [33;1m at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:876)
> [K[[36;1m04:07:17 [33;1mWARN]: [33;1m at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:183)
> [K[[36;1m04:07:17 [33;1mWARN]: [33;1m at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:109)
> [K[[36;1m04:07:17 [33;1mWARN]: [33;1m at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:859)
> [K[[36;1m04:07:17 [33;1mWARN]: [33;1m at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:853)
> [K[[36;1m04:07:17 [33;1mWARN]: [33;1m at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:119)
> [K[[36;1m04:07:17 [33;1mWARN]: [33;1m at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:839)
> [K[[36;1m04:07:17 [33;1mWARN]: [33;1m at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:773)
> [K[[36;1m04:07:17 [33;1mWARN]: [33;1m at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:276)
> [K[[36;1m04:07:17 [33;1mWARN]: [33;1m at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by SeanOMik** [comment]
It might be possible for someone to create a mod but I wouldn't know how to.

Make sure that the plugin is loaded properly with no errors during the bootup.

**Comment by SeanOMik** [comment]
Dead issue
