### ISSUE TITLE
Customizable death notifications

### ISSUE THREAD

**Issue by femboyfin** [SeanOMik/TamableFoxes#34]
It would be really nice to have config options to make death messages public instead of only sending them to the fox's owner and if the owner is offline having them notified automatically when they log back in (or letting you run a command every time a fox dies to use something like EssentialsX's mail system) would be really nice to have for QoL.

**Comment by SeanOMik** [comment]
I'll take a look at using EssentialsX's mail system.

Thanks for the suggestions!
