### ISSUE TITLE
Deleting items in 1.16.4

### ISSUE THREAD

**Issue by soxsrampage** [SeanOMik/TamableFoxes#35]
When holding a shield and shift clicking to try to give them a tool they will delete the tool and hold the shield. You can take the shield back but your tool will be gone

**Comment by SeanOMik** [comment]
Just to make sure, the fox was holding the shield and you tried to give it a tool? If that's what you were doing, I don't have any issues with it. What tools are you trying to give the fox?

**Comment by SeanOMik** [comment]
I think this issue was caused by the same issue that #37 had which is now fixed.
