### ISSUE TITLE
Path where the plugin saves the prefix.

### ISSUE THREAD

**Issue by ghost** [SeanOMik/TamableFoxes#36]
Hello!  Good morning / afternoon / evening, I have come to report a bug or error where the plugin prefix cannot be displayed or cannot be found, I have searched everything even in the src and I cannot find it.  Would you be so kind as to tell me where it is?  if it is in a place with the naked eye I apologize but I am not able to find it.

**Comment by SeanOMik** [comment]
The plugin doesn't support changing the prefix of the command. I'll take a look at implementing it when I have some time.

**Comment by SeanOMik** [comment]
Even though this is a really old issue, I did get around to adding it in [this release](https://github.com/SeanOMik/TamableFoxes/releases/tag/2.0.0-SNAPSHOT).
