### ISSUE TITLE
foxes sleeping

### ISSUE THREAD

**Issue by MagmaVRC** [SeanOMik/TamableFoxes#38]
can you add it were if you leave a tamed fox for a bit it sleeps or player cna make it sleep?

**Comment by SeanOMik** [comment]
I don't know how I could make it so the fox will randomly sleep without the plugin slowing down servers. I've thought about making it so a player can make a player sleep, but I'm not sure about the best way that the player would control that.

**Comment by MagmaVRC** [comment]
ah ok

**Comment by ChildoftheBeast** [comment]
Shift right click with empty hand for sleeping fox :3

**Comment by SeanOMik** [comment]
> 
> 
> Shift right click with empty hand for sleeping fox :3

That's a good idea! I didn't think about an empty hand. I'll take a look at implementing it when I get time.
