### ISSUE TITLE
Use NBT instead of SQLite to keep track of data?

### ISSUE THREAD

**Issue by itsfolf** [SeanOMik/TamableFoxes#4]
Since 1.14 Spigot has had the PersistentDataHolder API, here's [a small guide to it](https://www.spigotmc.org/threads/a-guide-to-1-14-persistentdataholder-api.371200/), I believe this API could be used to save the foxes' data directly to the entity's NBT removing the need for the SQLite database that is currently in use and can impact performance. I have looked around the code and haven't found anything that could make this change impossible but I'd like to get some input from you.

**Comment by SeanOMik** [comment]
Looks a lot better than using SQLite. It will take me some time to implement it, thanks for the suggestion!

**Comment by itsfolf** [comment]
@SeanOMik I have implemented this at https://github.com/fuwwy/TamableFoxes, however I haven't had the time to test it

**Comment by SeanOMik** [comment]
That looks good, I'll test is as soon as I have time

**Comment by SeanOMik** [comment]
I created a pull request and tested it, it seems to work great, thanks! I'll make an actual release and upload it to spigot.

**Comment by itsfolf** [comment]
@SeanOMik I have a question tho, why are the sleeping and sitting states saved separately? Aren't they already saved by default?

**Comment by SeanOMik** [comment]
I could've had just one column named state which stored "sleep" and "sit" but I felt like it was easier to just have two separate columns.
