### ISSUE TITLE
Feature Request: Cancel dealt damage to foxes

### ISSUE THREAD

**Issue by squishycat92** [SeanOMik/TamableFoxes#40]
Hi, thank you so much for this plugin, it's really cool and also great to have the foxes follow the player around! However, because of this, foxes are sometimes at risk of getting shot by other mobs, players, etc. A config option I'd like to see would perhaps make foxes effectively invincible.

I'm aware that this might be OP in vanilla servers, but I've noticed that many players would like to make their pets invincible in custom servers. Because of this, perhaps this option could be disabled by default and have a configuration in order to make foxes invincible.

Once again, thank you so much for this plugin! :D

**Comment by SeanOMik** [comment]
Sorry, but I don't think it would be used enough. Not to mention that I don't know if it's even possible.

**Comment by squishycat92** [comment]
Ah alrighty, thanks for considering though!
