### ISSUE TITLE
random sitting foxes [bug?][feature request]

### ISSUE THREAD

**Issue by ChildoftheBeast** [SeanOMik/TamableFoxes#43]
We're seeing an occasional fox sitting in the wild. i don't know if these are spawning as tamed with no owner and would be a bug, or if they're from players. 

A command to beable to see the owner of a fox they you're currently looking at would be really useful to see if this is a bug where we have ownerless foxes or if these little guys got abandoned.

**Comment by SeanOMik** [comment]
Are the foxes stuck as being sat down?

**Comment by ChildoftheBeast** [comment]
in the last ~2-3 weeks of play time, we've found 2 that were stuck as sitting, and checking their tags, they didn't have an owner marked.
