### ISSUE TITLE
Java 16 Support

### ISSUE THREAD

**Issue by femboyfin** [SeanOMik/TamableFoxes#44]
As [Mojang is updating to Java 16](https://minecraft.net/article/minecraft-snapshot-21w19a), that's going to become a minimum as of 1.17's release on [June 8th](https://minecraft.net/article/caves---cliffs--part-i-has-release-date-). Right now on Java 16, the plugin throws a variety of errors when trying to (for example) tame a fox. Once I'm home I'll put all the errors (with reproducable steps) I can find under this issue, but I thought it'd be a good idea to let you know just in case you hadn't heard about this already.

**Comment by SeanOMik** [comment]
For me, the plugin seems to work fine when running on Java 16. Could you show me the errors you're getting?

**Comment by femboyfin** [comment]
My bad, it was a confliction with another (outdated) plugin, sorry about that.

**Comment by SeanOMik** [comment]
No problem, have fun!
