### ISSUE TITLE
Fox attacks bug

### ISSUE THREAD

**Issue by Teasyx** [SeanOMik/TamableFoxes#47]
the fox still attacks the animals despite deactivation with attack-wild-animals: false

**Comment by SeanOMik** [comment]
What MC version and plugin version are you running?

**Comment by Teasyx** [comment]
I use the plugin on the 16.5 and on the latest version, the 1.9.2

**Comment by SeanOMik** [comment]
It seems to work fine for me. When you changed the option did you only reload the plugin or did you restart the server?

**Comment by SeanOMik** [comment]
This will be closed soon due to inactivity
