### ISSUE TITLE
[1.17] Accidentally exiting naming leaves no means to re-name

### ISSUE THREAD

**Issue by articwashere** [SeanOMik/TamableFoxes#51]
If the naming anvil window is accidentally exited, you are left with no way to rename the fox it seems?

Using a name tag will act as a work-around, but the name visibility does not persist.

**Comment by SeanOMik** [comment]
This will be fixed in the next release by forcing the player to set the foxes name and an ability to show the rename menu again when using a nametag on the fox (even if the nametag is named).
