### ISSUE TITLE
[1.17] Sleeping foxes teleport after player

### ISSUE THREAD

**Issue by articwashere** [SeanOMik/TamableFoxes#52]
Sleeping foxes does not stay stationary. Is this intentional?

When in sleeping state, they teleport after the player regardless

**Comment by SeanOMik** [comment]
That is not intentional and it's a bug. I'll fix it soon

**Comment by SeanOMik** [comment]
So after some testing, I was not able to reproduce this. Could you send a video or some steps from stop to finish of how you reproduce this bug?

**Comment by ghost** [comment]
https://user-images.githubusercontent.com/87051390/124691696-15111f80-de91-11eb-9255-2578d4e8e0ed.mp4

Not the person who originally reported, but I hope you don't me sending a video nonetheless.
I'm not entirely sure how this bug happened, but here are some details that might help:
- This is a 1.17 server with several plugins such as Geyser, Essentials, BetterSleeping, CMILib, BetterBooksPlugin, SkinsRestorer, GSIT, mcMMO, Gringotts, Vault, and Jobs Reborn
- I just downloaded this plugin today; I did forget to add the arguments in my server start script before running the server, but I made sure to do it after a quick restart
- The foxes were not spawned through commands or creative menu

**Comment by SeanOMik** [comment]
I don't mind at all, no worries! I didn't try to use naturally spawning foxes. Does the bug still occur after a server restart? I'll try to reproduce with naturally spawned foxes.

**Comment by articwashere** [comment]
I can add to this video and say this is the same behavior I'm experiencing. All by natural generated foxes

**Comment by SeanOMik** [comment]
Okay so, I kind of forgot I fixed this when I ran into it myself and thought I made a release to fix it, so the version I was using didn't have it and that's why I wasn't able to reproduce it. Anyway, I'll make a release soon with the fix sorry about wasting your time!

**Comment by SeanOMik** [comment]
Made the release, download [here](https://github.com/SeanOMik/TamableFoxes/releases/tag/2.1.0-SNAPSHOT), and have fun!
