### ISSUE TITLE
Tamable foxes does not work on 1.17.1 Purpur it seems.

### ISSUE THREAD

**Issue by articwashere** [SeanOMik/TamableFoxes#53]
I know the plugin doesnt officially state support for 1.17.1, but I would nonetheless mention that I have tried to deploy it on my 1.17.1 purpur server to no avail. A bunch of java exceptions are thrown at me and any command used shows internal errors + all foxes are gone.

**Comment by SeanOMik** [comment]
Yeah, 1.17.1 probably changed some things that break this plugin. I'll get to work on updating it soon, hopefully, they didn't make it too hard for me haha.

**Comment by SeanOMik** [comment]
Okay, this update was actually _super_ simple, like surprisingly simple. Anyway, I just made a release for 1.17.1 support [here](https://github.com/SeanOMik/TamableFoxes/releases/tag/2.1.1-SNAPSHOT).

**Comment by n0k0m3** [comment]
Still crash on Purpur 1.17.1. If i remove the Tamable plugins the server starts fine

[crash-2021-07-11_10.35.28-server.txt](https://github.com/SeanOMik/TamableFoxes/files/6797095/crash-2021-07-11_10.35.28-server.txt)
[server_screen.log](https://github.com/SeanOMik/TamableFoxes/files/6797104/server_screen.log)

**Comment by SeanOMik** [comment]
I don't think its caused my Tamable Foxes. In the server log, it looks like the custom entity replaces the fox entity successfully. It also works fine for me on the latest purpur build ([build 1262](https://purpur.pl3x.net/api/v1/purpur/1.17.1/latest/download))

A few questions:
* What plugins do you have installed?
* What purpur version are you using? The specific build would be super helpful.

**Comment by n0k0m3** [comment]
Interesting... I'm also using latest purpur 1262. Plugins installed are: WorldEdit, sleepmost, afkplus, tamablefoxes

**Comment by SeanOMik** [comment]
Do those errors happen on startup or when trying to spawn a fox?

**Comment by n0k0m3** [comment]
Happens at startup.

Edit 1:
I "fixed" it by killing all spawned foxes :(

Without the plugins loaded

```
> kill @e[type=fox]
[12:24:49 INFO]: Named entity EntityFox['Senko'/134, uuid='d77691ba-fd33-49a6-beba-f1c0c096214b', l='ServerLevel[world]', x=113.98, y=71.00, z=-283.98, cpos=[7, -18], tl=29210219, v=true, rR=null] died: Senko fell out of the world
[12:24:49 INFO]: Named entity EntityFox['Kirara'/158, uuid='9e305bf7-e607-452e-be8e-2aa92b9ff111', l='ServerLevel[world]', x=156.22, y=69.00, z=-269.40, cpos=[9, -17], tl=55166584, v=true, rR=null] died: Kirara fell out of the world
[12:24:49 INFO]: Killed 5 entities
```

Big sad but it seemed like somehow they got spawned outside of the world(??? doesn't make sense but that's what the log say)

Edit 2: Nevermind /spawntamablefox crashed the server and with same error log after spawning + startup

**Comment by SeanOMik** [comment]
Well when you kill things with the kill command, it says that they fell out of world.

**Comment by n0k0m3** [comment]
So apparently any foxes created with `/spawntamablefox` will cause the error

**Comment by SeanOMik** [comment]
Yeah, I thought it would. I'm actually able to reproduce this error so give me some time to debug it.

I think purpur does some weird patch that's causing this

**Comment by SeanOMik** [comment]
Okay, I think I fixed it. Try to download [this](https://drive.google.com/file/d/18RsNAQv53jS6n2_Yy8qdgS3GuwRSPEPd/view?usp=sharing)

**Comment by n0k0m3** [comment]
Yep worked perfectly. Thanks

**Comment by SeanOMik** [comment]
Awesome, glad to hear, have fun!
