### ISSUE TITLE
Crash report caused by plugin [Bug] 

### ISSUE THREAD

**Issue by ghost** [SeanOMik/TamableFoxes#55]
Today I received a crash report rooting from this plugin.
I included the report below for you, but let me list some details:
  I'm running the 2.1.0 snapshot.
  This is a 1.17 server, as usual.
  The owner of the fox that was being ticked (Clementine) went to sleep before the crash.  I am using the BetterSleeping3 plugin so only one player has to sleep to skip the night.  I assume that's why the other foxes weren't ticked.
  Clementine was sitting.

Crash report included below:
[crash-2021-07-11_16.44.08-server.txt](https://github.com/SeanOMik/TamableFoxes/files/6797926/crash-2021-07-11_16.44.08-server.txt)

Please let me know if you need the log as well.  From a quick scan, it looks like the only errors are from another plugin that I have yet to address.  (It's been like that for a while though so I doubt it's from that.)

**Comment by SeanOMik** [comment]
I'm not able to reproduce it even with the BetterSleeping plugin. Are you using a spigot fork, like paper, purpur, etc.? And I also wanted to make sure it's 1.17 and not 1.17.1 (they're both supported but it might help reproduce the crash). Could you also upload the full log?

**Comment by ghost** [comment]
No, I'm not using any Spigot fork.  And yes, this is a 1.17 server, since I wanted to wait a bit before updating to 1.17.1.

Heres the full log below:
[latest.log](https://github.com/SeanOMik/TamableFoxes/files/6804220/latest.log)

**Comment by ghost** [comment]
if it helps, this is what doing /ver in console gives me:

[13:51:08] [Server thread/INFO]: This server is running CraftBukkit version 3170-Spigot-a483d2c-ec116f6 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
[13:51:08] [Server thread/INFO]: You are 10 version(s) behind

**Comment by SeanOMik** [comment]
I had an idea. Try [this jar](https://drive.google.com/file/d/1HZiWOv1z9TJoecisnQA-XNKbcvJtIxmE/view?usp=sharing).

**Comment by ghost** [comment]
Apologies for the wait!  I, er, kind of got sucked into playing while testing the jar.

Seems like there's no more crashes!  I made sure to test going to bed with my foxes, all when they were sitting, sleeping, and standing.  Thanks :D

**Comment by SeanOMik** [comment]
No worries haha, glad it's working, and have fun!
