### ISSUE TITLE
[Bug] Spigot jar is still 2.1.1

### ISSUE THREAD

**Issue by femboyfin** [SeanOMik/TamableFoxes#56]
**Describe the bug**
The jar served by SpigotMC is still 2.1.1, not 2.1.2.

**To Reproduce**
1. Go to the [Tamable Foxes spigot resource page](https://www.spigotmc.org/resources/tamable-foxes-1-14-x-1-15-x-1-16-x-1-17-x.69537)
2. Click [Download Now](https://www.spigotmc.org/resources/tamable-foxes-1-14-x-1-15-x-1-16-x-1-17-x.69537/download?version=408583)
3. Test the plugin on a Purpur server or simply observe the jar name, `TamableFoxes_v2.1.1-SNAPSHOT.jar`.

**Expected behavior**
The Spigot resources downloads the latest jar version

**Errors**
N/A

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/18708515/125362185-ffeb3380-e35d-11eb-8ddf-c43b31166708.png)

**Versions**
MC: 1.17.1
Java: 
```
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)
```

**Additional context**
The jar from GitHub still works fine, I'm assuming the wrong jar was uploaded to Spigot by accident.

**Comment by SeanOMik** [comment]
Oops, I must've uploaded the wrong file. Also, thanks for using and following the template so well even though you didn't have to as strictly in this case.

Anyway, its fixed now, thanks!
