### ISSUE TITLE
Server crashes after any spawning any fox

### ISSUE THREAD

**Issue by articwashere** [SeanOMik/TamableFoxes#57]
The server throws java exceptions and then stops the server
Here is a log
[latest.log](https://github.com/SeanOMik/TamableFoxes/files/6804894/latest.log)

It should be fixed apparently with the newest update, but I think you forgot to attach the new version, since the file itself still says 2.1.1 and not 2.1.2. Regardless of that being a naming issue, I will open this bug report.

**Comment by SeanOMik** [comment]
If you're using Purpur, yes it's fixed. GitHub also has [releases](https://github.com/SeanOMik/TamableFoxes/releases) which didn't have the old jar file. I also fixed the jar on SpigotMC. Please tell me if that new version fixes it.

**Comment by SeanOMik** [comment]
Guessing this is fixed due to inactivity
