### ISSUE TITLE
[Bug] Presumed broken or a conflict?

### ISSUE THREAD

**Issue by xamionex** [SeanOMik/TamableFoxes#58]
**Describe the bug**
Try spawning a fox, gets error on latest minecraft version

**Errors**
[latest.log](https://github.com/SeanOMik/TamableFoxes/files/6813640/latest.log)
(note: It didn't crash the server I just stopped it)

**Versions**
MC: Paper (v102) on 1.17.1
Java: 
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)

**Additional context**
The startup argument was added

**Comment by SeanOMik** [comment]
Just tested on paper (build 102) and it worked fine. What plugins do you have installed?

**Comment by xamionex** [comment]
I'll start testing 1 by 1 since i have PlugManX installed

**Comment by xamionex** [comment]
This is weird, i just started it up and it worked
Is PAPI a dependency? Cos it's the only thing i updated

**Comment by SeanOMik** [comment]
No, PAPI isn't a dependency. Due to how the plugin modifies the server's code at runtime, PAPI might've been doing some weird thing that interferes with something that this plugin does. I'm glad you got it working though!

**Comment by xamionex** [comment]
![image](https://user-images.githubusercontent.com/57235791/125724777-66c926ff-f79a-496f-83e2-a55cd58d6393.png)

Recently modified/added: Green is updated plugin and red is added plugin

**Comment by xamionex** [comment]
I don't wanna see why it broke cos that'll take a while, so there's my plugin changes. Thank you! ^-^
