### ISSUE TITLE
JVM Argument

### ISSUE THREAD

**Issue by pokemonrocks9** [SeanOMik/TamableFoxes#59]
will there be an update in the future that removes this requirement in 1.17.1 to allow one to use on a host that doesnt allow changing of start.bat

**Comment by itsfolf** [comment]
@SeanOMik I found a method to replace fields on Java 16 without needing JVM arguments
https://github.com/fuwwy/TamableFoxes/blob/dev/src/main/java/net/seanomik/tamablefoxes/versions/FieldHelper.java

**Comment by SeanOMik** [comment]
Awesome! I'll put it onto this branch and mess with it. I'll be sure to give credit to you in the commit since you have a lot of other changes on your fork that aren't needed on the original.

**Comment by SeanOMik** [comment]
@pokemonrocks9 You no longer need to use program arguments in the [latest release](https://github.com/SeanOMik/TamableFoxes/releases/tag/2.1.4-SNAPSHOT). Enjoy!
