### ISSUE TITLE
[Bug] Could not save language.yml... Warning

### ISSUE THREAD

**Issue by femboyfin** [SeanOMik/TamableFoxes#62]
**Describe the bug**
There's a weird/unnecessary warning printed in console:
```
[Server thread/WARN]: [Tamablefoxes] Could not save language.yml to plugins\Tamablefoxes\language.yml because language.yml already exists.
```
It's sent one if language.yml doesn't exist (i.e. if the plugin was fresh-installed) and twice if language.yml does already exist.

**To Reproduce**
1. Install the plugin 
2. Start the server
3. Pay close attention to your console or check `latest.log` for the warning.
4. (To see the warning being printed twice) Restart the server and check `latest.log` again

**Expected behavior**
No warning should be printed (especially with a fresh-install of the plugin), because everything works fine and the file doesn't need to be overwritten anyways.

**Errors**
```
[13:44:05] [Server thread/INFO]: [Tamablefoxes] Loading Tamablefoxes v2.1.4-SNAPSHOT
[13:44:05] [Server thread/WARN]: [Tamablefoxes] Could not save language.yml to plugins\Tamablefoxes\language.yml because language.yml already exists.
[13:44:05] [Server thread/INFO]: [BingusSMP] Registering entity for MC Version v1_17_R1...
[13:44:05] [Server thread/INFO]: [Tamable Foxes] Replaced tamable fox entity!
```

**Screenshots**
N/A

**Versions**
MC: 
```
This server is running Purpur version git-Purpur-1330 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 158ae61 on ver/1.17.1)
```
Java: 
```
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)
```

**Additional context**
This has been an issue for a while (since early 1.16 builds), I'd assume there just isn't a check in place to see if the file exists before trying to create the default config but that's just a guess (nothing is overwritten to be clear).

**Comment by SeanOMik** [comment]
It has been an issue for a while, I just never really got to fix it since it didn't actually cause any issues so I eventually forgot about it haha. Well, it's fixed now and will be in the next release.

Thanks for making an issue!
