### ISSUE TITLE
[Bug] Tame fox

### ISSUE THREAD

**Issue by TheKlimoT** [SeanOMik/TamableFoxes#63]
1. Take chicken shtrips
2. Right Click fox
3. And kick player

LOG:
https://paste.helpch.at/uvixoqoqas.bash

**Versions**
MC: 1.16.5 Purpur
Java: jdk16

**Comment by SeanOMik** [comment]
Could you send the whole server log? I think there might've been an issue on startup.

**Comment by SeanOMik** [comment]
Closing stale issue
