### ISSUE TITLE
[Bug] Fox not sitting or sleeping

### ISSUE THREAD

**Issue by KanekiK3n** [SeanOMik/TamableFoxes#64]
**Describe the bug**
They don't sit nor sleep when right clicked and shift right clicked.

**To Reproduce**
1. right click/ shift right click

**Expected behavior**
They should sit when right clicked and sleep when shift right clicked

**Versions**
MC: 1.17.1
Java: VERSION 16.0.2+7-67

**Comment by SeanOMik** [comment]
Just to be sure, you did take them with raw chicken before trying to make them sit? If so, upload a log file

**Comment by KanekiK3n** [comment]
[latest.log](https://github.com/SeanOMik/TamableFoxes/files/7003459/latest.log)

**Comment by SeanOMik** [comment]
Was that a log when you tried to make them sit?
When taming the foxes, does the naming window popup and show properly?

**Comment by KanekiK3n** [comment]
Yes, but I'll send another one just to make sure it's the correct one. This one was from today right after trying it again.

I just discovered that I can make a freshly tamed tamable fox sit and sleep.
And yes when taming the windows shows up without issues.
In my case I need to use ctrl to make them sleep instead of shift, probably because I swapped the two.

https://user-images.githubusercontent.com/25288621/129952480-522ef6d2-6fe7-48d0-acc7-a5bf5e4e8496.mp4

[latest.log](https://github.com/SeanOMik/TamableFoxes/files/7009412/latest.log)

**Comment by SeanOMik** [comment]
Oh, so foxes that were previously tamed you can't make them sit. 

> In my case I need to use ctrl to make them sleep instead of shift, probably because I swapped the two.

Yeah, that's expected. Making a fox sleep isn't bound to the shift key, it's bound to whether the player is sneaking or not.

What version of the plugin are you using?

**Comment by KanekiK3n** [comment]
Correct, just tried it.
This is the version I'm using TamableFoxes_v2.1.5-SNAPSHOT.jar

**Comment by SeanOMik** [comment]
Hm, I'm not able to reproduce it. Is your server in offline mode?

**Comment by KanekiK3n** [comment]
It's in online mode, but just to be safe these are my settings:

#Minecraft server properties
#Wed Aug 18 21:53:08 CEST 2021
enable-jmx-monitoring=false
level-seed=
rcon.port=25575
enable-command-block=true
gamemode=survival
enable-query=false
generator-settings=
level-name=world
motd=\u2190Welcome to \u00A78The\u00A74 Clo\u00A76wn\u00A72 Wo\u00A73rld \u00A71Sa\u00A75ga\u00A7e\u2622\u00A7r\u2192\n\u00A7f\u00A7khell\u00A72\u00A7n1\u00A7f\u00A7n.\u00A7a\u00A7n17\u00A7f\u00A7n.\u00A72\u00A7n1\u00A7f\u00A7khell
query.port=25565
pvp=true
generate-structures=true
difficulty=normal
network-compression-threshold=512
max-tick-time=60000
require-resource-pack=false
max-players=20
use-native-transport=true
online-mode=true
enable-status=true
allow-flight=false
broadcast-rcon-to-ops=true
view-distance=18
max-build-height=256
server-ip=
resource-pack-prompt=
allow-nether=true
server-port=25565
enable-rcon=false
sync-chunk-writes=true
op-permission-level=4
server-name=Unknown Server
prevent-proxy-connections=false
resource-pack=https\://www.dropbox.com/s/k9290ch789lu6xu/VanillaTweaks_RP_17-8-21.zip?dl\=1
entity-broadcast-range-percentage=100
player-idle-timeout=30
rcon.password=
force-gamemode=false
debug=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
snooper-enabled=false
function-permission-level=2
level-type=default
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
resource-pack-sha1=CA75AE50F9BC7FFE93BB34E3B1F3E60100BE6F58
spawn-protection=0
max-world-size=29999984

**Comment by SeanOMik** [comment]
Tbh, I don't know what's happening. I'll make a tool for exporting some information about the fox you're looking at tomorrow, today I'm too busy.

**Comment by KanekiK3n** [comment]
Yeah no problem, I do have some new piece of information btw.
I could retame the tamed foxes with chicken.

**Comment by SeanOMik** [comment]
> 
> 
> Yeah no problem, I do have some new piece of information btw.
> I could retame the tamed foxes with chicken.

Oh, that's super weird. I think the owner UUID probably got cleared from the NBT then. Did you do something to your world or install a plugin or something inbetween when it was working fine and when it stopped working?

**Comment by KanekiK3n** [comment]
I only updated all the plugins, had some trouble with rwg but that's also fixed now.

**Comment by SeanOMik** [comment]
That's weird, idk how it got cleared, maybe one of the plugins you updated messed with it. 

If someone else has the same thing happen to them, please say so in this issue. I'll keep it open for now to see if anyone else has it happen to them.

**Comment by KanekiK3n** [comment]
Alright! I'll also keep an eye out for anything else in game. But I doubt anything else will happen so that's cool. 👍🏽
