### ISSUE TITLE
Forge Compatibility

### ISSUE THREAD

**Issue by AndyKitty8** [SeanOMik/TamableFoxes#65]
Will this plugin work with Forge?

**Comment by SeanOMik** [comment]
No, it's a plugin, not a mod. So unless you find some forge server that can run spigot plugins, no it won't work. If you do somehow, It *should* but I've never tested it for that.

**Comment by AndyKitty8** [comment]
Ok, thank you!

**Comment by AndyKitty8** [comment]
Oh I have another question. Is this plugin compatible with Shadew’s Foxes mod?

**Comment by SeanOMik** [comment]
No, it won't be since that mod adds a whole new entity replacing the vanilla one.

**Comment by AndyKitty8** [comment]
Alrighty, thanks.
