### ISSUE TITLE
[Feature] /givefox - Transfer foxes.

### ISSUE THREAD

**Issue by hirata-estate** [SeanOMik/TamableFoxes#66]
**Describe your feature request.**
Allows transferring of foxes, just like EssentialsX /givepet.
```
/givefox {player} - transfers the fox right-clicked after doing this command to the player entered.
```
Permission nodes:
```
tamablefoxes.give - lets them transfer foxes.
tamablefoxes.give.receive - allows them to have foxes transferred to them.
```
^ A player without the tamablefoxes.tame permission could just ask someone that has it to tame a fox and then transfer it to them. This can fix that/make it configurable.

**Additional context**
This not only allows the transferring of foxes, but also lets server admins transfer the foxes if the user encounters a UUID issue.

**Comment by SeanOMik** [comment]
Good idea, I'll implement it soon and notify you when its released.

**Comment by SeanOMik** [comment]
@ultraic-space This was just implemented in the [latest release](https://github.com/SeanOMik/TamableFoxes/releases/tag/2.2.0-SNAPSHOT). Check the readme to view the permissions though since I did change them slightly.
