### ISSUE TITLE
[Bug] Console spam from 1.18.1 patch

### ISSUE THREAD

**Issue by pokemonrocks9** [SeanOMik/TamableFoxes#69]
**Describe the bug**
Large amount of console spam blocking the server fromn letting people in 
**To Reproduce**
1. Place [...]
2. Take [...]
3. Click on [...] then [...]

**Expected behavior**
Lack of console spam allowing for lack of timeout commands
**Errors**
If any errors or stack traces appeared in the console, please link to them here. Please use Pastebin to post stack traces. Don't paste them into the issue.

[Sun, 12. Dec 2021 13:31:32 GMT WARN] at TamableFoxes_v2.2.1-SNAPSHOT.jar//net.seanomik.tamablefoxes.versions.version_1_18_1_R1.EntityTamableFox.fL(EntityTamableFox.java:177)
[Sun, 12. Dec 2021 13:31:37 GMT WARN] at jdk.internal.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
[Sun, 12. Dec 2021 13:31:37 GMT WARN] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Sun, 12. Dec 2021 13:31:37 GMT WARN] at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[Sun, 12. Dec 2021 13:31:37 GMT WARN] at TamableFoxes_v2.2.1-SNAPSHOT.jar//net.seanomik.tamablefoxes.versions.version_1_18_1_R1.EntityTamableFox.fL(EntityTamableFox.java:177)
[Sun, 12. Dec 2021 13:31:37 GMT WARN] at jdk.internal.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
[Sun, 12. Dec 2021 13:31:37 GMT WARN] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Sun, 12. Dec 2021 13:31:37 GMT WARN] at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[Sun, 12. Dec 2021 13:31:37 GMT WARN] at TamableFoxes_v2.2.1-SNAPSHOT.jar//net.seanomik.tamablefoxes.versions.version_1_18_1_R1.EntityTamableFox.fL(EntityTamableFox.java:177)
[Sun, 12. Dec 2021 13:31:37 GMT WARN] at jdk.internal.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
**Screenshots**

**Versions**
MC: 1.18.1
Java:  17

**Additional context**

**Comment by SeanOMik** [comment]
Are you using a fork of spigot (paper, purpur, etc)? Also, could you provide an entire log file? You can find it in `logs/latest.log`

**Comment by pokemonrocks9** [comment]
Paper 1.18.1 
https://www.dropbox.com/s/5ztth3jolx6q490/latest.log?dl=0
(It wouldnt let me upload the log)

**Comment by SeanOMik** [comment]
@pokemonrocks9 I was able to reproduce it, I think I fixed it. Try this jar file (unzip the file first) [TamableFoxes_v2.2.2-SNAPSHOT.zip](https://github.com/SeanOMik/TamableFoxes/files/7699134/TamableFoxes_v2.2.2-SNAPSHOT.zip) and tell me how it goes

**Comment by pokemonrocks9** [comment]
Works perfectly
Thank you!

**Comment by SeanOMik** [comment]
Awesome, I'll make a new release!
