### ISSUE TITLE
[Bug] Can't name tamed foxes in 1.18.2

### ISSUE THREAD

**Issue by Pecacheu** [SeanOMik/TamableFoxes#76]
Using the latest plugin version 2.2.4 with Paper 1.18.2. It works for the most part but I can't name a fox. The dialog opens up (looks like an anvil GUI, I type in the name, then click on the paper in the output slot... But then it just says "%NAME% is perfect!" in the console. The fox remains with the name "Fox" regardless.

Also, it seems like the `show-owner-in-fox-name` in the config is ignored. I have that set to true, but the name of the fox still displays as just "Fox"

**Versions**
MC: Paper 1.18.2
Java: OpenJDK 17.0.2

**Comment by SeanOMik** [comment]
Try to delete the `language.yml` in the plugins storage folder.
