### ISSUE TITLE
[Feature] Teleport Distance Option + Integration w/ Other Plugin

### ISSUE THREAD

**Issue by Pecacheu** [SeanOMik/TamableFoxes#77]
Also I wanted to open a separate issue for this because it's a feature request and not a bug, but I think there should be a setting to customize the teleport radius for the foxes. I feel like they teleport a bit too early for my taste, it needs to give the fox time to follow naturally so it looks less like they're "on a leash" so to speak.

Second of all, I was wondering if there's any sort of API for this plugin or if there's a way to see what Player UUID owns a given fox. Because I have a plugin of my own that it would be neat to integrate with this one. https://github.com/Pecacheu/MultiWorldPets

**Comment by SeanOMik** [comment]
> I feel like they teleport a bit too early for my taste, it needs to give the fox time to follow naturally so it looks less like they're "on a leash" so to speak.

I had the teleport distance set to the value it's set to since it's the same value that the wolf has.

> Second of all, I was wondering if there's any sort of API for this plugin or if there's a way to see what Player UUID owns a given fox.

There is not an API for it yet, however you can get the owner UUID with the NBT tag `OwnerUUID`. There's also a `Sitting` and `Sleeping` tag.
