### ISSUE TITLE
Plugin forgets tamed foxes

### ISSUE THREAD

**Issue by Pecacheu** [SeanOMik/TamableFoxes#8]
By the way I noticed another bug, so I'm making a new issue for it. It seems like the plugin just forgets fox's owners randomly. It happens not every time, but frequently when the server is restarted, even just a normal /stop and restart it often happens, and especially occurs when doing /reload.

Stranger still, sometimes it happens when I come back a few hours later / the next day, even though the server hasn't restarted. The plugin just forgot the fox was tamed, though the name still displays.

There must be some sort of bug in the saving / loading routine. Maybe you could somehow scan and add back foxes the plugin forgot about based on their names? Or you could add it as a command, like `/tamablefoxes rescan` perhaps.

**Comment by Pecacheu** [comment]
By the way, I also get this warning when reloading (though this doesn't happen when restarting)
```
Nag author: '<NoAuthorGiven>' of 'Tamablefoxes' about the following: This plugin is not properly shutting down its async tasks when it is being reloaded.  This may cause conflicts with the newly loaded version of the plugin
```

**Comment by SeanOMik** [comment]
What version are you using? 

I thought I put a warning saying to not reload but looks like I forgot to. Don't reload the plugin due to how it registers the custom entity.

**Comment by Pecacheu** [comment]
Well like I said the same thing happens if I close and restart the server as well, so it's not that.

Also I'd consider not supporting /reload a bug as well, I need to /reload sometimes to update plugin configs for plugins that don't have an individual plugin reloading command. It takes like 5+ minutes for the server to restart. Couldn't you detect the reload somehow and do whatever you need to do over again?

Also I'm using v1.5.3.

**Comment by SeanOMik** [comment]
Not supporting /reload is not a bug since it's intentional and there are several plugins that don't support it. There is no way to support it in the way this plugin works.

It's not a good idea to use /reload in general. Pretty sure spigot even gives you a message saying that it may cause issues.

I'll take a look at the not saving a tame thing.

**Comment by SeanOMik** [comment]
Failed to reproduce

**Comment by OakLaptop** [comment]
I also get this issue. Foxes will randomly become untamed and/or stand up.

**Comment by SeanOMik** [comment]
And you are running the newest version correct?

**Comment by OakLaptop** [comment]
I am running 1.14.4 with ViaVersion and am using the 1.3.2 version of the plugin as thats what it says to use on the Spigot page

**Comment by SeanOMik** [comment]
Your using the correct version for 1.14.4, but maybe try to update because that version isn't only old, but doesn't run well at all.

**Comment by SeanOMik** [comment]
I mean update to 1.15.2

**Comment by OakLaptop** [comment]
well i'm going to be updating to 1.16 when it comes out. I'll just wait till then

**Comment by itsfolf** [comment]
@SeanOMik On my fork of the plugin I've implemented the foxes in a different way using completely vanilla methods and they work much better (no issues with saving) and with less lag, I have made some changes to the plugin to fit my server so I can't PR but I thought you might want to have a look

**Comment by Pecacheu** [comment]
@fuwwy Does it also fix the odd issue of foxes running away from the player in survival mode even while sneaking? That kind of makes it difficult to actually tame them.

(Cute folf btw XD)

**Comment by itsfolf** [comment]
@Pecacheu It didn't fix that because I wasn't aware of it, but it should be fixed now, I'll eventually look fully into the fox AI
