### ISSUE TITLE
1.19+ Update

### ISSUE THREAD

**Issue by DrSnowPengu** [SeanOMik/TamableFoxes#80]
Hello,

TamableFox plugin needs updating to 1.19+

**Comment by DrSnowPengu** [comment]
@SeanOMik Hello, sorry to bother you but will you be updating tamable fox to 1.19? If so is there an eta?

**Comment by SeanOMik** [comment]
I just made a [release](https://github.com/SeanOMik/TamableFoxes/releases/tag/2.2.5-SNAPSHOT) for 1.19 support, enjoy!
