### ISSUE TITLE
[Bug] Error on startup when using 1.19.1

### ISSUE THREAD

**Issue by ItzPeto** [SeanOMik/TamableFoxes#83]
**Describe the bug**
Error on startup when using 1.19.1, plugin doesn't work

**To Reproduce**
1. Upgrade the server to 1.19.1
2. See the error message in console
3. Panic

**Errors**
https://pastebin.com/DZ2XWkdw

**Versions**
MC: 1.19.1 (Purpur)
Java: 17.0.1

**Comment by SeanOMik** [comment]
The mod didn't support 1.19.1, it does now in the [latest release](https://github.com/SeanOMik/TamableFoxes/releases/tag/2.2.6-SNAPSHOT) thanks to @mshipman.
