### ISSUE TITLE
[Feature] Update to 1.19.3

### ISSUE THREAD

**Issue by Surax23** [SeanOMik/TamableFoxes#89]
Hello.
Is there any plans to update plugin to 1.19.3?

**Comment by kjakkonrad** [comment]
i also connect myself to this question, when u post new update? we waiting :P

**Comment by SeanOMik** [comment]
A [new release](https://github.com/SeanOMik/TamableFoxes/releases) was just made for 1.19.3 support, have fun!

**Comment by kjakkonrad** [comment]
we love u bro !
