### ISSUE TITLE
[Feature] Update to 1.19.4

### ISSUE THREAD

**Issue by Shrek617** [SeanOMik/TamableFoxes#92]
Hello.
Is there any plans to update plugin to 1.19.4?

**Comment by Shrek616** [comment]
Where

**Comment by Shrek616** [comment]
UP

**Comment by SeanOMik** [comment]
I was busy with final exams and work, I just [released an update for 1.19.4](https://github.com/SeanOMik/TamableFoxes/releases/tag/2.2.9-SNAPSHOT)
