### ISSUE TITLE
1.19.4 support

### ISSUE THREAD

**Issue by pip-gato** [SeanOMik/TamableFoxes#94]
Hey, i wanted to add this to my server (1.19.4) but it doesnt work since the support only goes up to 1.19.2, could you update the support to be 1.19.4 please :)

**Comment by SeanOMik** [comment]
There's support for [1.19.3](https://github.com/SeanOMik/TamableFoxes/releases/tag/2.2.8-SNAPSHOT) and [1.19.4](https://github.com/SeanOMik/TamableFoxes/releases/tag/2.2.9-SNAPSHOT). I forget to post them on spigot so I'll do that now.
