### ISSUE TITLE
[Feature] Update to 1.20.1

### ISSUE THREAD

**Issue by DexterSK** [SeanOMik/TamableFoxes#99]
**Describe your feature request.**
Just support for new MC version

**Comment by SeanOMik** [comment]
I've been pretty busy with school and work recently, I hope to get this done this weekend, but no promises.

**Comment by DexterSK** [comment]
yup no problem, i already did it

**Comment by SeanOMik** [comment]
Oh awesome, could you make a pr with your changes then please?

**Comment by DexterSK** [comment]
sure.

You can merge them somehow? :D

https://github.com/DexterSK/TamableFoxes/tree/master/1_20_R1/net/seanomik/tamablefoxes/versions/version_1_20_1_R1

**Comment by SeanOMik** [comment]
Yeah that'll be fine, it's still easier than me updating it. I'll make sure to give you credit when I make a release tomorrow. Thanks!
